### ISSUE TITLE
Compiling problems

### ISSUE THREAD

**Issue by jgarzon3** [rsignell-usgs/rex2nc#2]
Dear Dr Signell,

I am a  Ph.D student and I am very interested in exploring the capabilities of the SLOSH model.  I found your code on Github to convert the outputs and I am trying to compile the code. However it is giving me an error in the netcdf_Spatial.c  script when it reads the static void netcdf_UpdateTimeUnitsSpatial line. 
It says     error: redefinition of ‘netcdf_UpdateTimeUnitsSpatial’

Please could you provide any guidance to fix this problem?

Thank you

**Comment by rsignell-usgs** [comment]
@JRDavisUF, do you think using an older version of netcdf Library would solve this problem?

**Comment by JRDavisUF** [comment]
No, I don't think its a NetCDF issue.  That's a rex2nc routine, not a NetCDF one.  In fact, If I had to guess, I'd say this person is compiling without NetCDF.  Take a look at the following:

netcdf_Spatial.c  
...
#ifndef HAVE_NETCDF_SUPPORT
static void netcdf_UpdateTimeUnitsSpatial(int year, int month, int day,  int hour, int min, int sec) {}
...
static void netcdf_UpdateTimeUnitsSpatial(int year, int month, int day, int hour, int min, int sec) {}
#else
...

The "fake prototype" for the routine mentioned netcdf_UpdateTimeUnitsSpatial  appears twice.  Assuming I'm correct and the code is being compiled without netcdf support, I'd bet getting rid of one of these would fix the problem as it does appear like function is being "redefined"

**Comment by jgarzon3** [comment]
JRDavisUF. Please find attached my config.log file, it might help. I dont see anything there related to NetCDF libraries though.
I compiled on the Stampede2 cluster, which has NetCDF libraries. 
I typed:
[config.log](https://github.com/rsignell-usgs/rex2nc/files/1499700/config.log)
 make NETCDF=enable

Thanks

**Comment by rsignell-usgs** [comment]
@JRDavisUF , I tried to build this on several systems with netcdf libs and failed.  And I can't remember if there are some installation tricks. 

I just did:
```
./configure 
make
```
and got the same error as @jgarzon3, even though the config.log shows the netcdf library found.

Can you give it a shot to see if you can still build it?

And if so, can you please provide your recipe?

**Comment by JRDavisUF** [comment]
OK, a couple of things here.  First, I tried configuring as suggested using just "./configure" and got the same redefinition error.  I then commented out one of the prototypes as I suggested and the error is gone and the code compiles fine.  As such, this is a bug in the source that needs to be fixed. 

Note, however, that this means simply using "./configure" will NOT compile the code using the netcdf routines in the code.  There is nothing in ANY of the configure stuff that I see to provide the needed CPP variable "HAVE_NETCDF_SUPPORT" (Note how the extra protoype is in a section which only gets compiled if this variable is not set).

I'm not sure where you got "NETCDF=enable" as a option.  I've seen this in other configure scripts, but I don't see anything in this particular script.  If its in there and it gives you access to the 32-bit version of NetCdf, then something like "./configure NETCDF=enable CFLAGS="-DHAVE_NETCDF_SUPPORT"  might give you a Makefile that would work.

I looked back through my notes to see how I compiled and it looks like there is a file missing in the distribution on GitHub which explains how to compile.  If one wants NetCDF support, one must supply the needed NetCdf configuration information to the configure script (as what NETCDF=enable would normally do) derived from the 32-bit version of nc-config.  For simplicity, I put the needed info in another script and ran the configure script from this one   An example of such a script  appears below.  Not how I specifically defined the HAVE_NETCDF_SUPPORT CPP variable to ensure the correct parts of the code get compiled.

*Don't forget, one must build a 32-bit executable...which means one must use the nc-config program from a 32-bit install of NetCdf*   (Yes, I'm mentioning this 3x because its important)

jrd

-----------------------------
```
#!/bin/sh

# Executable must be 32-bit.
# -std=c99  is necessary to get rid of long long warning in netcdf.h
#    But that causes problems with other stuff

# Make sure this is for the x86 (not x86_64) version of NetCdf
# Assumes nc-config is in the path.
#NC_CONFIG = "nc-config"
# Assumes nc-config is not in the path.
NC_CONFIG="/usr/local/netcdf/x86-gcc/netcdf-current/bin/nc-config"

# Get the commands that were used to compile netcdf
CC=`${NC_CONFIG} --cc`
LDFLAGS=`${NC_CONFIG} --libs`
CFLAGS=`${NC_CONFIG} --cflags`

# No NetCDF Available
#CFLAGS="${CFLAGS} -m32 -static"
# Have NetCDF and HDF
CFLAGS="${CFLAGS} -m32 -static -DHAVE_NETCDF_SUPPORT -DHAVE_HDF_SUPPORT"

# This should work, but LDFLAGS is not handled properly
#echo "CC=${CC}"
#echo "LDFLAGS=${LDFLAGS}"
#echo "CFLAGS=${CFLAGS}"
#./configure CC="${CC}" CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}"

echo "CC=${CC}"
echo "CFLAGS=${CFLAGS} ${LDFLAGS}"
./configure CC="${CC}" CFLAGS="${CFLAGS} ${LDFLAGS}"
```
----------------------------------
